// templates/dynamic_api_angular_app/frontend/src/app/app.component.ts
import { Component } from '@angular/core'
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app-shell">
      <header class="topbar">
        <a class="brand" routerLink="/">
          <span class="brand-mark">Qx</span>
          <span>
            <strong>Qornix Dynamic Angular</strong>
            <small>Backend API + Angular scaffold</small>
          </span>
        </a>
        <nav class="nav-links" aria-label="Main navigation">
          <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Home</a>
          <a routerLink="/backend-admin" routerLinkActive="active">Backend Admin</a>
          <a routerLink="/project-structure" routerLinkActive="active">Project Structure</a>
          <a href="/api/dynamic/openapi.json" target="_blank" rel="noreferrer">OpenAPI</a>
        </nav>
      </header>

      <main>
        <router-outlet></router-outlet>
      </main>
    </div>
  `
})
export class AppComponent {}

// templates/dynamic_api_vue_app/frontend/src/App.vue
<template>
  <div class="app-shell">
    <header class="topbar">
      <RouterLink class="brand" to="/">
        <span class="brand-mark">Qx</span>
        <span>
          <strong>Qornix Dynamic Vue</strong>
          <small>Backend API + Vue scaffold</small>
        </span>
      </RouterLink>
      <nav class="nav-links" aria-label="Main navigation">
        <RouterLink to="/">Home</RouterLink>
        <RouterLink to="/backend-admin">Backend Admin</RouterLink>
        <a href="/project-structure">Project Structure</a>
        <a href="/api/dynamic/openapi.json" target="_blank" rel="noreferrer">OpenAPI</a>
      </nav>
    </header>

    <main>
      <RouterView />
    </main>
  </div>
</template>
